#!/usr/bin/env python3
""" Async Comprehensions """

from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronously generates a list of numbers using an async generator.

    Returns:
        List[float]: A list of floats generated by the async generator.
    """
    return [num async for num in async_generator()]
